export const FILE_UPLOAD = "FILE_UPLOAD";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";

export const GET_FILE_LIST = "GET_FILE_LIST";
export const GET_FILE_LIST_SUCCESS = "GET_FILE_LIST_SUCCESS";
export const GET_FILE_LIST_FAILURE = "GET_FILE_LIST_FAILURE";

export const FILE_DELETE = "FILE_DELETE";
export const FILE_DELETE_SUCCESS = "FILE_DELETE_SUCCESS";
export const FILE_DELETE_FAILURE = "FILE_DELETE_FAILURE";

export const GET_DATA = "GET_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const DETAIL_MODAL_ON = "DETAIL_MODAL_ON";
export const DETAIL_MODAL_OFF = "DETAIL_MODAL_OFF";

export const DETAIL_MODAL_REQ = "DETAIL_MODAL_REQ";
export const DETAIL_MODAL_REQ_SUCCESS = "DETAIL_MODAL_REQ_SUCCESS";
export const DETAIL_MODAL_REQ_FAILURE = "DETAIL_MODAL_REQ_FAILURE";

export const GET_DETAIL = "GET_DETAIL";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";
export const GET_DETAIL_FAILURE = "GET_DETAIL_FAILURE";
